name: IndividualMobRemover
version: '${project.version}'
main: me.serbob.individualmobremover.IndividualMobRemover
api-version: 1.19
authors: [ Serbob ]
description: A plugin that each mob you add won't be able to spawn naturally.
commands:
  restrictmob:
    description: Restricts the chosen mob to not naturally spawn anymore.
permissions:
  individualmobremover.restrictmob:
      default: op
